set_property IOSTANDARD LVCMOS33 [get_ports {z[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {z[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {z[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {z[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {z[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {z[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {z[6]}]
set_property PACKAGE_PIN W17 [get_ports {x[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[0]}]
set_property PACKAGE_PIN W16 [get_ports {x[2]}]
set_property PACKAGE_PIN V16 [get_ports {x[1]}]
set_property PACKAGE_PIN V17 [get_ports {x[0]}]
set_property PACKAGE_PIN V15 [get_ports {sel[1]}]
set_property PACKAGE_PIN W15 [get_ports {sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]


set_property PACKAGE_PIN W7 [get_ports {z[6]}]
set_property PACKAGE_PIN W6 [get_ports {z[5]}]
set_property PACKAGE_PIN U8 [get_ports {z[4]}]
set_property PACKAGE_PIN V8 [get_ports {z[3]}]
set_property PACKAGE_PIN U5 [get_ports {z[2]}]
set_property PACKAGE_PIN V5 [get_ports {z[1]}]
set_property PACKAGE_PIN U7 [get_ports {z[0]}]
