set_property PACKAGE_PIN V16 [get_ports a2]
set_property PACKAGE_PIN V17 [get_ports a1]
set_property PACKAGE_PIN W16 [get_ports b1]
set_property PACKAGE_PIN W17 [get_ports b2]
set_property PACKAGE_PIN W15 [get_ports cin]
set_property PACKAGE_PIN U19 [get_ports cout]
set_property PACKAGE_PIN U16 [get_ports x1]
set_property PACKAGE_PIN E19 [get_ports x2]
set_property IOSTANDARD LVCMOS33 [get_ports a1]
set_property IOSTANDARD LVCMOS33 [get_ports a2]
set_property IOSTANDARD LVCMOS33 [get_ports b2]
set_property IOSTANDARD LVCMOS33 [get_ports cout]
set_property IOSTANDARD LVCMOS33 [get_ports b1]
set_property IOSTANDARD LVCMOS33 [get_ports cin]
set_property IOSTANDARD LVCMOS33 [get_ports x1]
set_property IOSTANDARD LVCMOS33 [get_ports x2]


