set_property IOSTANDARD LVCMOS33 [get_ports {count[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[0]}]
set_property PACKAGE_PIN W7 [get_ports {count[6]}]
set_property PACKAGE_PIN W6 [get_ports {count[5]}]
set_property PACKAGE_PIN U8 [get_ports {count[4]}]
set_property PACKAGE_PIN V8 [get_ports {count[3]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN L1 [get_ports clk_led]
set_property PACKAGE_PIN V17 [get_ports direction]
set_property PACKAGE_PIN T17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk_led]
set_property IOSTANDARD LVCMOS33 [get_ports direction]
set_property IOSTANDARD LVCMOS33 [get_ports reset]


set_property PACKAGE_PIN U5 [get_ports {count[2]}]
set_property PACKAGE_PIN V5 [get_ports {count[1]}]
set_property PACKAGE_PIN U7 [get_ports {count[0]}]
