set_property PACKAGE_PIN V17 [get_ports x0]
set_property PACKAGE_PIN V16 [get_ports x1]
set_property PACKAGE_PIN T1 [get_ports y0]
set_property PACKAGE_PIN R2 [get_ports y1]
set_property PACKAGE_PIN U16 [get_ports z0]
set_property PACKAGE_PIN E19 [get_ports z1]
set_property PACKAGE_PIN L1 [get_ports cout]
set_property IOSTANDARD LCVMOS33 [get ports x0]
set_property IOSTANDARD LCVMOS33 [get ports x1]
set_property IOSTANDARD LCVMOS33 [get ports y0]
set_property IOSTANDARD LCVMOS33 [get ports y1]
set_property IOSTANDARD LCVMOS33 [get ports z0]
set_property IOSTANDARD LCVMOS33 [get ports z1]
set_property IOSTANDARD LCVMOS33 [get ports cout]